import app from '@adonisjs/core/services/app'
import { defineConfig } from '@adonisjs/vite'

/**
 * Vite configuration for the AdonisJS backend.
 *
 * The "@adonisjs/vite" service reads `manifestFile` with plain `fs` calls — the
 * path is NOT resolved for you. A relative path therefore depends on the
 * process working directory: it worked locally (run from the project root,
 * where "public/vite" exists) but broke inside the production container, where
 * only the built output is present and the app runs from a different directory.
 * The symptom was a blank page with:
 *
 *   EdgeError: Missing manifest file. Make sure to first create a build
 *
 * `app.makePath` resolves against the application root, so the manifest is found
 * from any working directory: in production the root is `build/`, where
 * "ace build" copies `public/**` as a meta file.
 */
const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this
   * directory. The path should be relative from
   * the application root.
   */
  // Keep customer-facing brand assets in public/assets; Vite output lives separately.
  buildDirectory: 'public/vite',

  /**
   * The path to the manifest file generated by the
   * "vite build" command.
   */
  manifestFile: app.makePath('public/vite/.vite/manifest.json'),

  /**
   * Feel free to change the value of the "assetsUrl" to
   * point to a CDN in production.
   */
  assetsUrl: '/vite',

  /**
   * HTML attributes to add to script tags generated by Vite.
   */
  scriptAttributes: {
    /**
     * Defer script execution until the HTML is fully parsed.
     * Improves page load performance.
     */
    defer: true,
  },
})

export default viteBackendConfig
